{"name": "test_rerun", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_rerun.py:11: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_rerun.py:11: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\n\n..\\venv\\lib\\site-packages\\six.py:718: FailedAssumption"}, "start": 1631178973135, "stop": 1631178973287, "uuid": "ed0cfe5e-9541-4594-9c1d-3d1a42b1bbc2", "historyId": "47c35f179f4b9f2c17e761a436dbbee0", "testCaseId": "558bc7562212911663d26c2ca57bd815", "fullName": "test_rerun#test_rerun", "labels": [{"name": "suite", "value": "test_rerun"}, {"name": "host", "value": "DESKTOP-GRKQKVO"}, {"name": "thread", "value": "50228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_rerun"}]}